### ISSUE TITLE
EWS URL hard-coding & Expected behavior

### ISSUE THREAD

**Issue by shAFXr** [MicrosoftDocs/memdocs#20]
Hello Team,
Clarification is required in the following KB:https://docs.microsoft.com/en-us/mem/intune/protect/troubleshoot-exchange-connector-common-problems#check-autodiscovery
When the EWS URL is hard-coded, the client establishes a TLSv1 connection even after applying the recommended mitigation per: https://github.com/MicrosoftDocs/IntuneDocs/issues/3563 

With the registry entry created; I am still seeing the following failures--
SendEmail - error :    at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.ValidateAndEmitRequest(HttpWebRequest& request)
   at Microsoft.Exchange.WebServices.Data.SimpleServiceRequestBase.InternalExecute()
   at Microsoft.Exchange.WebServices.Data.MultiResponseServiceRequest`1.Execute()
   at Microsoft.Exchange.WebServices.Data.ExchangeService.InternalCreateItems(IEnumerable`1 items, FolderId parentFolderId, Nullable`1 messageDisposition, Nullable`1 sendInvitationsMode, ServiceErrorHandling errorHandling)
   at Microsoft.Exchange.WebServices.Data.Item.InternalCreate(FolderId parentFolderId, Nullable`1 messageDisposition, Nullable`1 sendInvitationsMode)
   at Microsoft.Exchange.WebServices.Data.EmailMessage.InternalSend(FolderId parentFolderId, MessageDisposition messageDisposition)
   at Microsoft.SystemCenter.Online.Mobile.Services.Exchange.Agent.ExchangeCommands.SendEmail(String fromEmail, String fromEmailPw, String ewsUrl, String toEmail, String customerText, NetworkCredential adminCred, String lsuAddress, String accountName, IEnumerable`1 easDeviceList, String upn, String userId, IEnumerable`1 deviceActions)
----
send email has Error :    at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.ValidateAndEmitRequest(HttpWebRequest& request)
   at Microsoft.Exchange.WebServices.Data.SimpleServiceRequestBase.InternalExecute()
   at Microsoft.Exchange.WebServices.Data.MultiResponseServiceRequest`1.Execute()
   at Microsoft.Exchange.WebServices.Data.ExchangeService.InternalCreateItems(IEnumerable`1 items, FolderId parentFolderId, Nullable`1 messageDisposition, Nullable`1 sendInvitationsMode, ServiceErrorHandling errorHandling)
   at Microsoft.Exchange.WebServices.Data.Item.InternalCreate(FolderId parentFolderId, Nullable`1 messageDisposition, Nullable`1 sendInvitationsMode)
   at Microsoft.Exchange.WebServices.Data.EmailMessage.InternalSend(FolderId parentFolderId, MessageDisposition messageDisposition)
   at Microsoft.SystemCenter.Online.Mobile.Services.Exchange.Agent.ExchangeCommands.SendEmail(String fromEmail, String fromEmailPw, String ewsUrl, String toEmail, String customerText, NetworkCredential adminCred, String lsuAddress, String accountName, IEnumerable`1 easDeviceList, String upn, String userId, IEnumerable`1 deviceActions)
   at Microsoft.SystemCenter.Online.Mobile.Services.Exchange.Agent.ExchangeCommands.SendNotificationToBlockedDevices(IExchangeRunspace rs, ConditionalAccessDeviceList list, NetworkCredential adminCred, String emailFooter, String notificationFromEmail, String notificationEmailPw, String ewsUrl, String lsuAddress, String accountName)
----
ProcessConditionalAccessWithNotificationCommand failed to send notification to email (EmailAddress). Exception Microsoft.Exchange.WebServices.Data.ServiceRequestException: The request failed. The underlying connection was closed: An unexpected error occurred on a send. ---&gt; System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---&gt; System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---&gt; System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.FixedSizeReader.ReadPacket(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Security.SslState.StartReceiveBlob(Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.CheckCompletionBeforeNextReceive(ProtocolToken message, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   at System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   at System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   at System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.GetResponse()
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.Emit(HttpWebRequest& request)
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.ValidateAndEmitRequest(HttpWebRequest& request)
   --- End of inner exception stack trace ---
   at Microsoft.Exchange.WebServices.Data.ServiceRequestBase.ValidateAndEmitRequest(HttpWebRequest& request)
   at Microsoft.Exchange.WebServices.Data.SimpleServiceRequestBase.InternalExecute()
   at Microsoft.Exchange.WebServices.Data.MultiResponseServiceRequest`1.Execute()
   at Microsoft.Exchange.WebServices.Data.ExchangeService.InternalCreateItems(IEnumerable`1 items, FolderId parentFolderId, Nullable`1 messageDisposition, Nullable`1 sendInvitationsMode, ServiceErrorHandling errorHandling)
   at Microsoft.Exchange.WebServices.Data.Item.InternalCreate(FolderId parentFolderId, Nullable`1 messageDisposition, Nullable`1 sendInvitationsMode)
   at Microsoft.Exchange.WebServices.Data.EmailMessage.InternalSend(FolderId parentFolderId, MessageDisposition messageDisposition)
   at Microsoft.SystemCenter.Online.Mobile.Services.Exchange.Agent.ExchangeCommands.SendEmail(String fromEmail, String fromEmailPw, String ewsUrl, String toEmail, String customerText, NetworkCredential adminCred, String lsuAddress, String accountName, IEnumerable`1 easDeviceList, String upn, String userId, IEnumerable`1 deviceActions)
   at Microsoft.SystemCenter.Online.Mobile.Services.Exchange.Agent.ExchangeCommands.SendNotificationToBlockedDevices(IExchangeRunspace rs, ConditionalAccessDeviceList list, NetworkCredential adminCred, String emailFooter, String notificationFromEmail, String notificationEmailPw, String ewsUrl, String lsuAddress, String accountName)
   at Microsoft.SystemCenter.Online.Mobile.Services.Exchange.Agent.ExchangeCommands.&lt;&gt;c__DisplayClassbd.&lt;ProcessConditionalAccessWithNotificationCommand&gt;b__b4(ConditionalAccessDeviceList conditionalAccessList, CancellationToken cancelToken)

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: c08834b8-fcb3-49c9-331e-c1a052982ca4
* Version Independent ID: 94ead8b3-89d1-3c80-7ac6-8551415461c5
* Content: [Troubleshoot common problems for the Intune Exchange connector - Microsoft Intune](https://docs.microsoft.com/en-us/mem/intune/protect/troubleshoot-exchange-connector-common-problems#feedback)
* Content Source: [memdocs/intune/protect/troubleshoot-exchange-connector-common-problems.md](https://github.com/MicrosoftDocs/memdocs/blob/master/memdocs/intune/protect/troubleshoot-exchange-connector-common-problems.md)
* Service: **microsoft-intune**
* Sub-service: **protect**
* Technology: ****
* GitHub Login: @Brenduns
* Microsoft Alias: **brenduns**

**Comment by Brenduns** [comment]
@shAFXr   I’ve checked with our engineering team, and they confirm that the registry change has been successful in resolving this for customers who also have hardcoded the URL. That suggests that something else is in play for this to be an issue in your environment. Unfortunately, we can’t provide support nor an investigation of this issue via this documentation feedback format, but we want you to get to resources that can assist. 

There are a couple of options available to provide the best level of support for this: 
- Post your issue on [Microsoft Intune forums](https://social.technet.microsoft.com/Forums/en-US/home?forum=microsoftintuneprod). These are moderated by our community MVPs who are very experienced, knowledgeable, and helpful. 
- Use [How to get support for Microsoft Intune](https://docs.microsoft.com/intune/get-support) to open a case with professional support. 
- Contact your Microsoft Premier team, such as a Premier Field Engineer or Technical Account Manager. 
I'm closing this issue as there's nothing actionable for docs at this time.

**Comment by shAFXr** [comment]
Hello @Brenduns, this has been posted for clarification and suggests more than one entry is required, and that have been "heard to work". Thank you. https://techcommunity.microsoft.com/t5/intune-customer-success/support-tip-how-to-update-your-intune-exchange-connector-to-use/ba-p/1239463
