### ISSUE TITLE
Known Issue for Community Hub crashing the Console (v2203 and upwards)

### ISSUE THREAD

**Issue by cvoigt** [MicrosoftDocs/memdocs#3087]
Another issue that I can reproduce 100% is the console crashing when opening the Community Hub.
I've reported this a few times in the past through uservoice (back in the day) and the frown function but it hasn't been fixed yet :( I'll send out another frown today.

It can be reproduced by using a custom Security Role that does have "Community Hub: Read/Download" permissions but otherwise has a more limited set of permissions (including Create on SMS_Scripts).
While https://docs.microsoft.com/en-gb/mem/configmgr/core/servers/manage/community-hub#permissions states that there are no other "special" permissions required this clearly does not seem to be the case.
The positive-test for this is to additionally assign the Read-Only Analyst Role to the same Administrative User and then the Console does *not* crash.

SmsAdminUI.log shows the following trace for the crash:
```
[1, PID:12348][08/29/2022 16:44:05] :System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source)
   at Microsoft.ConfigurationManagement.AdminConsole.Community.CommunityHubScriptManager.GetTopLevelSiteCode()
   at Microsoft.ConfigurationManagement.AdminConsole.Community.CommunityHubScriptManager.GetInitializationProperties()
   at Microsoft.ConfigurationManagement.AdminConsole.Community.StorePage.GetHeaders()
   at Microsoft.ConfigurationManagement.AdminConsole.Community.StorePage.Initialize()
   at Microsoft.ConfigurationManagement.AdminConsole.HomePageView.OverviewPageControl.CreateContent()
   at Microsoft.ConfigurationManagement.AdminConsole.HomePageView.OverviewPageControl..ctor(OverviewControllerBase controllerBase)
   at Microsoft.ConfigurationManagement.AdminConsole.HomePageView.HomePageViewController.EndInit()
   at Microsoft.EnterpriseManagement.ConsoleFramework.ComponentFactory.CreateComponentWithDefaultConstructor(ConstructorInfo constructor, IContainer parentContainer, String componentName, EventHandler`1 componentInitializeProcedure)
   at Microsoft.EnterpriseManagement.ConsoleFramework.ComponentFactory.CreateComponent(Type componentType, IContainer parentContainer, String componentName, EventHandler`1 componentInitializeProcedure)
   at Microsoft.EnterpriseManagement.ConsoleFramework.FrameworkServices.ServiceTableRecord.CreateComponent(Type componentType, String componentName, EventHandler`1 componentInitializeProcedure)
   at Microsoft.EnterpriseManagement.ConsoleFramework.ViewConstructor.CreateViewController(Object parent, Object view, Type controllerType)
   at Microsoft.EnterpriseManagement.ConsoleFramework.ViewConstructor.BeginShow(ShowViewContext showViewContext, AsyncCallback callback, Object state)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.CreateAndShowViewCore(ShowViewContext showViewContext)
   at Microsoft.EnterpriseManagement.ConsoleFramework.Wpf.GenericWpfViewConstructor.ShowViewOperation.ShowView(ShowViewContext showViewContext)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at System.Windows.Window.Show()
   at System.Windows.Window.ShowDialog()
   at Microsoft.EnterpriseManagement.ConsoleFramework.WindowManager.GenericWpfWindowConstructor.BeginShow(ShowViewContext showViewContext, Object parent, Object view, AsyncCallback callback, Object state)
   at Microsoft.EnterpriseManagement.ConsoleFramework.ViewConstructor.BeginShow(ShowViewContext showViewContext, AsyncCallback callback, Object state)
   at Microsoft.EnterpriseManagement.ConsoleFramework.WindowManager.WpfWindowRecord.ShowWindow()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at System.Windows.Application.Run(Window window)
   at Microsoft.EnterpriseManagement.ConsoleFramework.ConsoleApplication.LaunchWindow()
   at Microsoft.EnterpriseManagement.ConsoleFramework.ConsoleApplication.Run()
   at Microsoft.ConfigurationManagement.AdminConsole.Program.Main()

```

---
#### Document details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 6fac7d23-fe47-b861-656a-8fedddf87246
* Version Independent ID: 0bb21e00-8a0c-cdb1-2f0c-1f0e5a738a1b
* Content: [Community hub and GitHub - Configuration Manager](https://docs.microsoft.com/en-gb/mem/configmgr/core/servers/manage/community-hub#community-hub-doesnt-load)
* Content Source: [memdocs/configmgr/core/servers/manage/community-hub.md](https://github.com/MicrosoftDocs/memdocs/blob/main/memdocs/configmgr/core/servers/manage/community-hub.md)
* Product: **configuration-manager**
* Technology: **configmgr-other**
* GitHub Login: @mestew
* Microsoft Alias: **mstewart**

**Comment by cvoigt** [comment]
Went a little bit deeper and I think I found the culprit: Security Scopes.
Sent this feedback as a frown through the console as well. ID 867c0359-9b51-4b93-bbda-8dd74a735c0b

The configmgr console crashes when opening the Community hub IF the user does not have the Default scope assigned.
In the other feedback I thought I had it traced down to permissions but it was actually the Security Scope.

Repro:
- administrative user with read-only analyst role and the Security Scope "Default" => Community hub loads
- create a custom security scope "test"
- remove the "Default" security scope for the administrative user and add the "test" security scope
- restart the console
- open the Community hub => crash with the exception documented above
- remove the "test" security scope, add the "Default" security scope from the administrative user
- open the Community hub => loads fine

I can now reliably repro this on Console version 5.2203.1063.1500 and multiple primary sites.
